"""empty message

Revision ID: 52d0b6eead10
Revises: b4b3747225c3
Create Date: 2016-03-31 09:39:38.574139

"""

# revision identifiers, used by Alembic.
revision = '52d0b6eead10'
down_revision = 'b4b3747225c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
